postgresql:
  image: tobi312/rpi-postgresql:9.4
  environment:
    - POSTGRES_USER=sonar
    - POSTGRES_PASSWORD=xaexohquaetiesoo
    - POSTGRES_DB=sonar
  volumes:
    - /media/usbraid/docker/sonarqube:/var/lib/postgresql/data
  ports:
    - "5432:5432"
sonarqube:
  image: paperinik/rpi-sonarqube:latest
#  build: ./
#  dockerfile: Dockerfile
  links:
    - postgresql:db
  environment:
    - DB_USER=sonar
    - DB_PASS=xaexohquaetiesoo
    - DB_NAME=sonar
  ports:
    - "9400:9000"
    - "443"
